language: ruby
rvm:
- 1.8.7
- 2.0.0
- 2.1.0
script: bundle exec rake spec
branches:
  only:
  - master
  - "/^issues\\/.*$/"
  - dev
notifications:
  email:
  - arusso@berkeley.edu
  slack:
    secure: TTrTXSnS4esBiupqT/j/Y3UyLx+0683MCpyp5hIUQ0x/jc27RMco5xNj1/Gyp7VQLskRpdsOLZ4jNzKHDrM2Rkokr3ubm15v0nBo1ORN39/Suw2OnVMmfC00cdeqMGlxGlryerBtyiqP17hSi1TeFti9Vj6HILRqErtFe+Am918=
env:
- PUPPET_VERSION="~> 3.8.0"
- PUPPET_VERSION="~> 3.8.0" PARSER="future"
- PUPPET_VERSION="~> 4.1.0"
- PUPPET_VERSION="~> 4.2.0"
- PUPPET_VERSION="~> 4.3.0"
matrix:
  exclude:
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.1.0"
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.2.0"
  - rvm: 1.8.7
    env: PUPPET_VERSION="~> 4.3.0"
